project_id = "wwgvwwiwmfxqifnsayas"

[functions.create-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = false

[functions.device-heartbeat]
verify_jwt = false

[functions.device-pair]
verify_jwt = true

[functions.content-sync]
verify_jwt = false

[functions.device-bind-screen]
verify_jwt = true